export const locales = ["pt-BR", "en"] as const
export type Locale = (typeof locales)[number]

export function normalizeLocale(value: string | null | undefined): Locale {
  return value?.toLowerCase().startsWith("en") ? "en" : "pt-BR"
}

const ptBR = {
  "common.save": "Salvar", "common.saving": "Salvando...", "common.cancel": "Cancelar", "common.edit": "Editar", "common.archive": "Arquivar", "common.notDefined": "Não definido", "common.comingSoon": "Em breve",
  "nav.home": "Início", "nav.dashboard": "Dashboard", "nav.today": "Hoje", "nav.inbox": "Caixa de entrada", "nav.calendar": "Calendário", "nav.planning": "Planejamento", "nav.purpose": "Propósito", "nav.areas": "Áreas", "nav.goals": "Metas", "nav.projects": "Projetos", "nav.routines": "Rotinas", "nav.processes": "Processos", "nav.execution": "Execução", "nav.tasks": "Tarefas", "nav.habits": "Hábitos", "nav.knowledge": "Conhecimento", "nav.library": "Biblioteca", "nav.studies": "Estudos", "nav.content": "Conteúdo", "nav.reviews": "Revisões", "nav.dailyReview": "Revisão diária", "nav.weeklyReview": "Revisão semanal", "nav.monthlyReview": "Revisão mensal", "nav.system": "Sistema", "nav.ai": "IA", "nav.settings": "Configurações",
  "search.full": "Buscar no sistema...", "search.short": "Buscar...", "search.prompt": "O que você precisa fazer?", "search.empty": "Nenhum resultado encontrado.", "search.quickActions": "Ações rápidas", "search.navigation": "Navegação", "search.newTask": "Nova tarefa", "search.newProject": "Novo projeto", "search.newNote": "Nova nota",
  "capture.button": "Capturar", "capture.title": "Captura rápida", "capture.description": "Adicione uma ideia, tarefa ou nota rápida à caixa de entrada.", "capture.content": "Conteúdo", "capture.placeholder": "Escreva o que você deseja lembrar...",
  "login.signIn": "Entrar", "login.signUp": "Criar conta", "login.name": "Nome", "login.email": "E-mail", "login.password": "Senha", "login.wait": "Aguarde...", "login.createFirst": "Criar minha primeira conta", "login.haveAccount": "Já tenho uma conta",
  "dashboard.hello": "Olá", "dashboard.ready": "Seu sistema está pronto para receber o que importa.", "dashboard.tasks": "Tarefas", "dashboard.goals": "Metas", "dashboard.schedule": "Agenda", "dashboard.none": "Nenhum registro", "dashboard.focus": "Foco do dia", "dashboard.focusEmpty": "Suas tarefas prioritárias aparecerão aqui.", "dashboard.createTask": "Criar tarefa", "dashboard.priorityProjects": "Projetos prioritários", "dashboard.projectsEmpty": "Crie seu primeiro projeto para acompanhar o progresso.", "dashboard.viewProjects": "Ver projetos", "dashboard.goalProgress": "Progresso de metas", "dashboard.goalsEmpty": "Defina uma meta conectada a uma área da sua vida.", "dashboard.setGoal": "Definir meta", "dashboard.scheduleEmpty": "Nenhum evento programado para hoje.", "dashboard.openCalendar": "Abrir calendário",
  "areas.subtitle": "Organize as dimensões importantes da sua vida.", "areas.new": "Nova área", "areas.name": "Nome", "areas.description": "Descrição", "areas.empty": "Nenhuma área criada ainda.", "areas.noDescription": "Sem descrição", "areas.edit": "Editar área", "areas.saveChanges": "Salvar alterações",
  "settings.title": "Configurações", "settings.subtitle": "Perfil, idioma e sessão da sua conta.", "settings.language": "Idioma", "settings.languageHelp": "A alteração será aplicada a todo o sistema.", "settings.portuguese": "Português (Brasil)", "settings.english": "English", "settings.timezone": "Fuso horário", "settings.logout": "Sair", "settings.user": "Usuário",
  "module.subtitle": "Este módulo está sendo preparado para seus dados reais.",
} as const

export type TranslationKey = keyof typeof ptBR
const en: Record<TranslationKey, string> = {
  "common.save": "Save", "common.saving": "Saving...", "common.cancel": "Cancel", "common.edit": "Edit", "common.archive": "Archive", "common.notDefined": "Not defined", "common.comingSoon": "Coming soon",
  "nav.home": "Home", "nav.dashboard": "Dashboard", "nav.today": "Today", "nav.inbox": "Inbox", "nav.calendar": "Calendar", "nav.planning": "Planning", "nav.purpose": "Purpose", "nav.areas": "Areas", "nav.goals": "Goals", "nav.projects": "Projects", "nav.routines": "Routines", "nav.processes": "Processes", "nav.execution": "Execution", "nav.tasks": "Tasks", "nav.habits": "Habits", "nav.knowledge": "Knowledge", "nav.library": "Library", "nav.studies": "Studies", "nav.content": "Content", "nav.reviews": "Reviews", "nav.dailyReview": "Daily review", "nav.weeklyReview": "Weekly review", "nav.monthlyReview": "Monthly review", "nav.system": "System", "nav.ai": "AI", "nav.settings": "Settings",
  "search.full": "Search the system...", "search.short": "Search...", "search.prompt": "What do you need to do?", "search.empty": "No results found.", "search.quickActions": "Quick actions", "search.navigation": "Navigation", "search.newTask": "New task", "search.newProject": "New project", "search.newNote": "New note",
  "capture.button": "Capture", "capture.title": "Quick capture", "capture.description": "Add an idea, task, or quick note to your inbox.", "capture.content": "Content", "capture.placeholder": "Write down what you want to remember...",
  "login.signIn": "Sign in", "login.signUp": "Create account", "login.name": "Name", "login.email": "Email", "login.password": "Password", "login.wait": "Please wait...", "login.createFirst": "Create my first account", "login.haveAccount": "I already have an account",
  "dashboard.hello": "Hello", "dashboard.ready": "Your system is ready for what matters.", "dashboard.tasks": "Tasks", "dashboard.goals": "Goals", "dashboard.schedule": "Schedule", "dashboard.none": "No records", "dashboard.focus": "Today's focus", "dashboard.focusEmpty": "Your priority tasks will appear here.", "dashboard.createTask": "Create task", "dashboard.priorityProjects": "Priority projects", "dashboard.projectsEmpty": "Create your first project to track progress.", "dashboard.viewProjects": "View projects", "dashboard.goalProgress": "Goal progress", "dashboard.goalsEmpty": "Set a goal connected to an area of your life.", "dashboard.setGoal": "Set goal", "dashboard.scheduleEmpty": "No events scheduled for today.", "dashboard.openCalendar": "Open calendar",
  "areas.subtitle": "Organize the important dimensions of your life.", "areas.new": "New area", "areas.name": "Name", "areas.description": "Description", "areas.empty": "No areas created yet.", "areas.noDescription": "No description", "areas.edit": "Edit area", "areas.saveChanges": "Save changes",
  "settings.title": "Settings", "settings.subtitle": "Your account profile, language, and session.", "settings.language": "Language", "settings.languageHelp": "The change will be applied throughout the system.", "settings.portuguese": "Português (Brasil)", "settings.english": "English", "settings.timezone": "Time zone", "settings.logout": "Sign out", "settings.user": "User",
  "module.subtitle": "This module is being prepared for your real data.",
}

export const dictionaries: Record<Locale, Record<TranslationKey, string>> = { "pt-BR": ptBR, en }
export function getDictionary(locale: Locale) { return dictionaries[locale] }
